# Custom Layers

Layers without Parameters

In [2]:
import torch
from torch import nn
from torch.nn import functional as F

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

Incorporate our layer as a component
in constructing more complex models

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(-4.6566e-09, grad_fn=<MeanBackward0>)

Layers with Parameters

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.8220,  0.1001, -0.0904],
        [ 0.1903, -0.4939,  0.5376],
        [ 1.4183, -0.5977, -0.4229],
        [ 1.0218, -0.8922,  0.0336],
        [-1.1032,  1.4305, -0.1898]], requires_grad=True)

Directly carry out forward propagation calculations using custom layers

In [7]:
linear(torch.rand(2, 5))

tensor([[2.6373e+00, 0.0000e+00, 0.0000e+00],
        [1.6540e+00, 1.2983e-03, 0.0000e+00]])

Construct models using custom layers

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[14.8508],
        [14.2191]])