# Custom Layers

Layers without Parameters

In [2]:
import torch
from torch import nn
from torch.nn import functional as F

class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

Incorporate our layer as a component
in constructing more complex models

In [4]:
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(-7.4506e-09, grad_fn=<MeanBackward0>)

Layers with Parameters

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.1973, -0.1610,  0.6770],
        [-0.1364,  2.3956,  0.4189],
        [ 1.0787, -0.1981,  0.5461],
        [ 1.7291,  0.6809, -0.3381],
        [-0.9100, -0.4145,  0.1638]], requires_grad=True)

Directly carry out forward propagation calculations using custom layers

In [7]:
linear(torch.rand(2, 5))

tensor([[1.5176, 0.0000, 0.4326],
        [0.1521, 0.0000, 0.0000]])

Construct models using custom layers

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])