# GPUs

View the graphics card information

In [1]:
!nvidia-smi

Mon Mar  7 23:15:33 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.27.04    Driver Version: 460.27.04    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla V100-SXM2...  Off  | 00000000:00:1B.0 Off |                    0 |
| N/A   41C    P0    50W / 300W |      0MiB / 16160MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   1  Tesla V100-SXM2...  Off  | 00000000:00:1C.0 Off |                    0 |
| N/A   

|   2  Tesla V100-SXM2...  Off  | 00000000:00:1D.0 Off |                    0 |
| N/A   48C    P0    59W / 300W |   1442MiB / 16160MiB |      9%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
|   3  Tesla V100-SXM2...  Off  | 00000000:00:1E.0 Off |                    0 |
| N/A   39C    P0    52W / 300W |      0MiB / 16160MiB |      1%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                                  |
|  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
|        ID   ID                        

Computing Devices

In [2]:
import torch
from torch import nn

torch.device('cpu'), torch.device('cuda'), torch.device('cuda:1')

(device(type='cpu'), device(type='cuda'), device(type='cuda', index=1))

Query the number of available GPUs

In [3]:
torch.cuda.device_count()

2

Define two convenient functions that allow us
to run code even if the requested GPUs do not exist

In [4]:
def try_gpu(i=0):  
    """Return gpu(i) if exists, otherwise return cpu()."""
    if torch.cuda.device_count() >= i + 1:
        return torch.device(f'cuda:{i}')
    return torch.device('cpu')

def try_all_gpus():  
    """Return all available GPUs, or [cpu(),] if no GPU exists."""
    devices = [torch.device(f'cuda:{i}')
             for i in range(torch.cuda.device_count())]
    return devices if devices else [torch.device('cpu')]

try_gpu(), try_gpu(10), try_all_gpus()

(device(type='cuda', index=0),
 device(type='cpu'),
 [device(type='cuda', index=0), device(type='cuda', index=1)])

Query the device where the tensor is located

In [5]:
x = torch.tensor([1, 2, 3])
x.device

device(type='cpu')

Store a tensor on the GPU

In [6]:
X = torch.ones(2, 3, device=try_gpu())
X

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')

Create a random tensor on the second GPU

In [7]:
Y = torch.rand(2, 3, device=try_gpu(1))
Y

tensor([[0.1216, 0.6211, 0.1657],
        [0.4750, 0.0351, 0.3881]], device='cuda:1')

If we want to compute `X + Y`,
we need to decide where to perform this operation

In [8]:
Z = X.cuda(1)
print(X)
print(Z)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')
tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:1')


The data are on the same GPU
(both `Z` and `Y` are),
we can add them up

In [9]:
Y + Z

tensor([[1.1216, 1.6211, 1.1657],
        [1.4750, 1.0351, 1.3881]], device='cuda:1')

In [10]:
Z.cuda(1) is Z

True

Neural Networks and GPUs

In [12]:
net = nn.Sequential(nn.Linear(3, 1))
net = net.to(device=try_gpu())

net(X)

tensor([[-0.8494],
        [-0.8494]], device='cuda:0', grad_fn=<AddmmBackward0>)

Confirm that the model parameters are stored on the same GPU

In [13]:
net[0].weight.data.device

device(type='cuda', index=0)