# Custom Layers



In [1]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

Layers without Parameters

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

Incorporate our layer as a component
in constructing more complex models

In [5]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(-8.3819e-09, grad_fn=<MeanBackward0>)

Layers with Parameters

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.5519, -0.3220,  1.2418],
        [ 0.3559,  2.2357, -0.5870],
        [ 1.1292, -0.0048, -0.7610],
        [-1.5225, -0.2633,  0.1360],
        [-1.8041, -0.6308, -0.0188]], requires_grad=True)

Directly carry out forward propagation calculations using custom layers

In [8]:
linear(torch.rand(2, 5))

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.1040]])

Construct models using custom layers

In [9]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])