# Custom Layers

Layers without Parameters

In [2]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

Incorporate our layer as a component
in constructing more complex models

In [3]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

/home/d2l-worker/miniconda3/envs/d2l-en-release-0/lib/python3.9/site-packages/torch/nn/modules/lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [4]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(-9.3132e-10, grad_fn=<MeanBackward0>)

Layers with Parameters

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[ 0.2803,  0.4214,  0.1135],
        [-1.6947,  0.4963, -0.1225],
        [-1.1451, -0.6529, -0.9109],
        [-1.2034,  0.7811,  0.0789],
        [ 1.1655,  2.1892,  1.7039]], requires_grad=True)

Directly carry out forward propagation calculations using custom layers

In [7]:
linear(torch.rand(2, 5))

tensor([[0.0000, 1.3874, 0.0000],
        [0.0000, 1.8211, 0.0000]])

Construct models using custom layers

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[8.4128],
        [5.0333]])