# Custom Layers



In [1]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

Layers without Parameters

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

Incorporate our layer as a component
in constructing more complex models

In [5]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(-3.7253e-09, grad_fn=<MeanBackward0>)

Layers with Parameters

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.0508, -0.3592,  0.0689],
        [-0.6911,  0.9781,  0.7885],
        [ 0.3686, -0.6090,  0.7788],
        [ 0.2550,  0.1543, -0.7385],
        [ 0.7041, -0.5031,  0.6874]], requires_grad=True)

Directly carry out forward propagation calculations using custom layers

In [8]:
linear(torch.rand(2, 5))

tensor([[0.1612, 0.0000, 1.7147],
        [0.7104, 0.0000, 1.7341]])

Construct models using custom layers

In [9]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])