# Custom Layers

Layers without Parameters

In [2]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l


class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

Incorporate our layer as a component
in constructing more complex models

In [3]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

/home/d2l-worker/miniconda3/envs/d2l-en-release-1/lib/python3.8/site-packages/torch/nn/modules/lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


In [4]:
Y = net(torch.rand(4, 8))
Y.mean()

tensor(0., grad_fn=<MeanBackward0>)

Layers with Parameters

In [6]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-0.1768,  0.5718,  1.3372],
        [-0.0800, -0.3124,  0.5639],
        [ 1.0192,  1.8009,  1.0995],
        [ 1.2927,  2.0420, -0.0564],
        [-1.1036,  1.4116,  1.9683]], requires_grad=True)

Directly carry out forward propagation calculations using custom layers

In [7]:
linear(torch.rand(2, 5))

tensor([[0.0000, 3.3582, 1.4402],
        [0.2795, 3.7836, 0.7976]])

Construct models using custom layers

In [8]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])