# Custom Layers



In [1]:
import torch
from torch import nn
from torch.nn import functional as F
from d2l import torch as d2l

Layers without Parameters

In [3]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()

    def forward(self, X):
        return X - X.mean()

layer = CenteredLayer()
layer(torch.tensor([1.0, 2, 3, 4, 5]))

tensor([-2., -1.,  0.,  1.,  2.])

Incorporate our layer as a component
in constructing more complex models

In [5]:
net = nn.Sequential(nn.LazyLinear(128), CenteredLayer())

Y = net(torch.rand(4, 8))
Y.mean()

tensor(0., grad_fn=<MeanBackward0>)

Layers with Parameters

In [7]:
class MyLinear(nn.Module):
    def __init__(self, in_units, units):
        super().__init__()
        self.weight = nn.Parameter(torch.randn(in_units, units))
        self.bias = nn.Parameter(torch.randn(units,))

    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[-1.2894e+00,  6.5869e-01, -1.3933e+00],
        [ 7.2590e-01,  7.1593e-01,  1.8115e-03],
        [-1.5900e+00,  4.1654e-01, -1.3358e+00],
        [ 2.2732e-02, -2.1329e+00,  1.8811e+00],
        [-1.0993e+00,  2.9763e-01, -1.4413e+00]], requires_grad=True)

Directly carry out forward propagation calculations using custom layers

In [8]:
linear(torch.rand(2, 5))

tensor([[0.0000, 1.7772, 0.0000],
        [0.0000, 1.0303, 0.0000]])

Construct models using custom layers

In [9]:
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[0.],
        [0.]])