# Parameter Management

We start by focusing on an MLP with one hidden layer

In [1]:
import torch
from torch import nn

net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(), nn.LazyLinear(1))
X = torch.rand(size=(2, 4))
net(X).shape

/home/d2l-worker/miniconda3/envs/d2l-en-release-1/lib/python3.8/site-packages/torch/nn/modules/lazy.py:178: UserWarning: Lazy modules are a new feature under heavy development so changes to the API or functionality can happen at any moment.
  warnings.warn('Lazy modules are a new feature under heavy development '


torch.Size([2, 1])

Parameter Access

In [2]:
net[2].state_dict()

OrderedDict([('weight',
              tensor([[-0.0020, -0.2192, -0.1979,  0.1038,  0.2019, -0.2588,  0.2396, -0.3146]])),
             ('bias', tensor([0.2685]))])

Targeted Parameters

In [3]:
type(net[2].bias), net[2].bias.data

(torch.nn.parameter.Parameter, tensor([0.2685]))

In [4]:
net[2].weight.grad == None

True

All Parameters at Once

In [5]:
[(name, param.shape) for name, param in net.named_parameters()]

[('0.weight', torch.Size([8, 4])),
 ('0.bias', torch.Size([8])),
 ('2.weight', torch.Size([1, 8])),
 ('2.bias', torch.Size([1]))]

Tied Parameters

In [6]:
shared = nn.LazyLinear(8)
net = nn.Sequential(nn.LazyLinear(8), nn.ReLU(),
                    shared, nn.ReLU(),
                    shared, nn.ReLU(),
                    nn.LazyLinear(1))
net(X)
print(net[2].weight.data[0] == net[4].weight.data[0])
net[2].weight.data[0, 0] = 100
print(net[2].weight.data[0] == net[4].weight.data[0])

tensor([True, True, True, True, True, True, True, True])
tensor([True, True, True, True, True, True, True, True])
